from typing import Any, Dict

from sqlalchemy.orm import Session

from src.agent.article_composer import compose_article
from src.agent.article_adapter import composer_result_to_article
from src.retrieval.publish_kb import publish_article
from src.retrieval.ingest import sync_kb
from src.db.knowledge_capture_service import record_knowledge_capture


def capture_human_resolution(
    incident_snapshot: Dict[str, Any],
    human_solution: str,
    article_number: str,
    category: str,
    service: str = "general",
    security_level: str = "internal",
    execution_identifier: str | None = None,
    db: Session | None = None,
) -> Dict[str, Any]:
    """
    Capture a human-provided incident resolution and close the
    knowledge loop through ServiceNow and Qdrant.

    Flow:
        human solution
            -> Article Composer
            -> canonical Article
            -> ServiceNow publish + verification
            -> Qdrant sync
            -> audit record
    """

    if not human_solution or not human_solution.strip():
        raise ValueError("human_solution is required")

    # 1. Convert the human resolution into a structured article.
    composed = compose_article(
        incident_snapshot=incident_snapshot,
        human_solution=human_solution,
    )

    # 2. Convert the Composer result into the canonical Article model.
    article = composer_result_to_article(
        composed=composed,
        article_number=article_number,
        category=category,
        service=service,
        security_level=security_level,
    )

    # 3. Publish and verify the article in ServiceNow.
    #
    # publish_article() performs the read-back verification internally.
    servicenow_result = publish_article(article)

    # 4. Only start Qdrant synchronization after ServiceNow
    #    publication has been successfully verified.
    try:
        qdrant_result = sync_kb()

    except Exception as exc:
        error_message = str(exc)

        # ServiceNow contains the article, but Qdrant synchronization
        # failed. Record this as a partial success when audit context
        # is available.
        if execution_identifier and db:
            record_knowledge_capture(
                db=db,
                execution_reference=execution_identifier,
                status="partial_success",
                article_number=servicenow_result.get(
                    "article_number",
                    article_number,
                ),
                article_sys_id=servicenow_result.get("sys_id"),
                qdrant_point_ids=[],
                error=error_message,
            )

        return {
            "status": "partial_success",
            "article": composed,
            "article_number": article_number,
            "servicenow": servicenow_result,
            "qdrant": {
                "status": "failed",
                "error": error_message,
            },
            "consistency": (
                "servicenow_published_qdrant_sync_failed"
            ),
        }

    # 5. Get the deterministic Qdrant point IDs generated by sync_kb().
    qdrant_point_ids = qdrant_result.get(
        "point_ids",
        [],
    )

    # 6. Record the successful knowledge-capture event.
    if execution_identifier and db:
        record_knowledge_capture(
            db=db,
            execution_reference=execution_identifier,
            status="completed",
            article_number=servicenow_result.get(
                "article_number",
                article_number,
            ),
            article_sys_id=servicenow_result.get("sys_id"),
            qdrant_point_ids=qdrant_point_ids,
        )

    return {
        "status": "completed",
        "article": composed,
        "article_number": article_number,
        "servicenow": servicenow_result,
        "qdrant": qdrant_result,
        "consistency": "synchronized",
    }