"""S2.3 adapter for the published S2.2 StateManager facade.

The worker receives only the confirmed S2.1 incident payload. Runtime
composition must inject an S2.2-generated execution identifier separately;
this adapter never derives it from payload fields. Retry-state lifecycle
selection also remains explicit at composition time.
"""

from dataclasses import dataclass
from typing import Callable, Protocol


class StateManagerForWorker(Protocol):
    """S2.2 StateManager methods used by the S2.3 persistence adapter."""

    def create_retry_state(
        self,
        execution_reference: str,
        attempt_count: int,
        last_error: str | None = None,
        next_attempt_time: object | None = None,
    ) -> object:
        """Create retry tracking state."""

    def update_retry_state(
        self,
        retry_state_id: int,
        attempt_count: int,
        last_error: str | None = None,
        next_attempt_time: object | None = None,
    ) -> object:
        """Update retry tracking state."""

    def record_failure(
        self,
        execution_reference: str,
        failing_node: str,
        error_class: str,
        message: str,
        retry_count: int = 0,
    ) -> object:
        """Persist terminal or exhausted failure context."""


RetryStateOperation = Callable[
    [StateManagerForWorker, str, int, BaseException], object
]


def execution_reference_from_execution(execution: object) -> str:
    """Return the UUID generated by S2.2's ``create_execution`` result."""
    execution_identifier = getattr(execution, "execution_identifier", None)
    if not isinstance(execution_identifier, str) or not execution_identifier.strip():
        raise ValueError("execution.execution_identifier must be a non-empty string")
    return execution_identifier


def create_retry_state_operation(
    state_manager: StateManagerForWorker,
    execution_reference: str,
    retries_completed: int,
    error: BaseException,
) -> object:
    """Map one retry event to S2.2's create API when explicitly selected."""
    return state_manager.create_retry_state(
        execution_reference=execution_reference,
        attempt_count=retries_completed + 1,
        last_error=str(error),
        next_attempt_time=None,
    )


def update_retry_state_operation(retry_state_id: int) -> RetryStateOperation:
    """Return an S2.2 update operation for an externally retained state row."""

    def operation(
        state_manager: StateManagerForWorker,
        execution_reference: str,
        retries_completed: int,
        error: BaseException,
    ) -> object:
        del execution_reference
        return state_manager.update_retry_state(
            retry_state_id=retry_state_id,
            attempt_count=retries_completed + 1,
            last_error=str(error),
            next_attempt_time=None,
        )

    return operation


@dataclass(frozen=True)
class StateManagerRecorder:
    """Bind explicit execution context to the injected S2.2 persistence calls."""

    state_manager: StateManagerForWorker
    execution_reference: str
    failing_node: str
    retry_state_operation: RetryStateOperation

    def record_retry(
        self,
        accepted_incident: object,
        retries_completed: int,
        error: BaseException,
    ) -> None:
        """Persist a retry using the caller-selected S2.2 retry operation."""
        del accepted_incident
        self.retry_state_operation(
            self.state_manager,
            self.execution_reference,
            retries_completed,
            error,
        )

    def record_failure(
        self,
        accepted_incident: object,
        retries_completed: int,
        error: BaseException,
    ) -> None:
        """Persist terminal or exhausted worker failure via S2.2."""
        del accepted_incident
        self.state_manager.record_failure(
            execution_reference=self.execution_reference,
            failing_node=self.failing_node,
            error_class=type(error).__name__,
            message=str(error),
            retry_count=retries_completed,
        )
